### ISSUE TITLE
Update jade template for Card

### ISSUE THREAD

**Issue by ben-scully** [ben-scully/mma-tcg-client-side#8]
`<div class="card">
        <img class="cardTemplate" src="http://orig08.deviantart.net/a4af/f/2015/017/1/2/neutral_legendary_monster_empty_card_by_demaretc-d8ea24s.png" >
        <div class="name">Conor McGregor</div>
        <div class="imageContainer">
          <img class="image" src="http://media.ufc.tv/fighter_images/Conor_McGregor/MCGREGOR_CONOR.png" alt="Conor">
        </div>
        <div class="rating">80</div>
      </div>`

**Comment by oliver-jk-redding** [comment]
Thanks, done.
